### ISSUE TITLE
Link to your github.io page

### ISSUE THREAD

**Issue by gorazd** [adelerossi/adelerossi.github.io#1]
Please put the link to your github.io page in the website field of your repository.
The Edit button on the right.

![Screenshot 2020-04-28 22 17 58](https://user-images.githubusercontent.com/192416/80533626-38436380-899e-11ea-8e98-ac7d611fa79f.png)

Mark this issue as closed once it's fixed.

**Comment by adelerossi** [comment]
I did it, please check it! Thank you so much
Adele

**Comment by gorazd** [comment]
I can see it, thank you.

Please close the issue as it is fixed.

**Comment by adelerossi** [comment]
okay thank you! 
i had some problems with the layout of my portfolio, i’m fixing it with the help of a graphic designer, but it easy to code and braces we checked it and i’m starting now
Thank you for your patience

**Comment by gorazd** [comment]
That is good to hear, remember you too are a graphic designer.

If you need an opinion I am at your disposal.

**Comment by adelerossi** [comment]
oh yes thank you so I will send you to night after the workshop!
