### ISSUE TITLE
Images Slider 

### ISSUE THREAD

**Issue by adelerossi** [adelerossi/adelerossi.github.io#2]
@gorazd I want this type of effects to images
https://xd.adobe.com/view/3ac62757-57bd-4658-59d9-8c08a76215b9-4cf7/

I think I need JS

**Comment by gorazd** [comment]
It's a great idea.

Let's use a placeholder image for now and later we can use a Javascript library.

For example:


### Lory
Touch enabled minimalistic slider written in vanilla JavaScript.

https://github.com/meandmax/lory


### Slick
the last carousel you'll ever need

https://github.com/kenwheeler/slick/
